name: CI/CD Pipeline

# Trigger the pipeline on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK (for Spring Boot application)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Run tests
    - name: Run tests
      run: mvn test

  # Deploy step (Optional)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run this job after the build job succeeds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run spring boot locally
      run: java -jar target/$(ls target | grep -E '.*\.jar$')
        

